# Generated by Django 3.0.8 on 2020-07-17 15:10

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('m08', 'Monday, 8:00 - 9:59'), ('m10', 'Monday, 10:00 - 11:59'), ('m12', 'Monday, 12:00 - 13:59'), ('m14', 'Monday, 14:00 - 15:59'), ('m16', 'Monday, 16:00 - 17:59'), ('m18', 'Monday, 18:00 - 19:59'), ('m20', 'Monday, 20:00 - 21:59'), ('t08', 'Tuesday, 8:00 - 9:59'), ('t10', 'Tuesday, 10:00 - 11:59'), ('t12', 'Tuesday, 12:00 - 13:59'), ('t14', 'Tuesday, 14:00 - 15:59'), ('t16', 'Tuesday, 16:00 - 17:59'), ('t18', 'Tuesday, 18:00 - 19:59'), ('t20', 'Tuesday, 20:00 - 21:59'), ('w08', 'Wednesday, 8:00 - 9:59'), ('w10', 'Wednesday, 10:00 - 11:59'), ('w12', 'Wednesday, 12:00 - 13:59'), ('w14', 'Wednesday, 14:00 - 15:59'), ('w16', 'Wednesday, 16:00 - 17:59'), ('w18', 'Wednesday, 18:00 - 19:59'), ('w20', 'Wednesday, 20:00 - 21:59'), ('th08', 'Thursday, 8:00 - 9:59'), ('th10', 'Thursday, 10:00 - 11:59'), ('th12', 'Thursday, 12:00 - 13:59'), ('th14', 'Thursday, 14:00 - 15:59'), ('th16', 'Thursday, 16:00 - 17:59'), ('th18', 'Thursday, 18:00 - 19:59'), ('th20', 'Thursday, 20:00 - 21:59')], default=(), max_length=118),
            preserve_default=False,
        ),
    ]
