# Generated by Django 3.0.8 on 2020-07-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0003_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=14, verbose_name='phone'),
        ),
    ]
